include-fragments = true

accept = ["200..=299", "429"]

exclude  = [
    # disabled
    "^https://github.com/newrelic/nrdot-collector-components/discussions",
    # private org links
    "^https://www.github.com/newrelic/dbi",
    "^https://www.github.com/newrelic/ohai",
    # exclude top-level README image links
    "https://github.com/newrelic/opensource-website/raw/main/src/images/",

]

# better to be safe and avoid failures
max-retries = 6
